# Project Name
TARGET = spiral2.0

# Sources
CPP_SOURCES = spiral2.0.cpp

# Library Locations
# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

